services:
  bff-app:
    container_name: task-manager-bff-app
    build: .
    image: ricardobgx/task-manager-bff-app
    restart: always
    environment:
      TASK_MANAGER_BFF_PORT: ${TASK_MANAGER_BFF_APP_PORT}
      TASK_MANAGER_BFF_URL: ${TASK_MANAGER_BFF_APP_URL}
      TASK_MANAGER_BFF_ISSUER_URL: ${TASK_MANAGER_BFF_APP_ISSUER_URL}
      TASK_MANAGER_BFF_AUTH_SERVER_CLIENT_ID: ${TASK_MANAGER_BFF_APP_AUTH_SERVER_CLIENT_ID}
      TASK_MANAGER_BFF_AUTH_SERVER_CLIENT_SECRET: ${TASK_MANAGER_BFF_APP_AUTH_SERVER_CLIENT_SECRET}
      TASK_MANAGER_BFF_PROFILES_API_URL: ${TASK_MANAGER_BFF_APP_PROFILES_API_URL}
      TASK_MANAGER_BFF_TASKS_API_URL: ${TASK_MANAGER_BFF_APP_TASKS_API_URL}
    networks:
      - task-manager-network
    ports:
      - ${TASK_MANAGER_BFF_APP_PORT}:${TASK_MANAGER_BFF_APP_PORT}
